apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vexxy-premium

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - postgresql.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
